# Generated by Django 5.2.14 on 2026-05-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_loginotp_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billitem",
            name="image_url",
            field=models.TextField(blank=True),
        ),
    ]
