# Generated by Django 5.2.14 on 2026-05-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="gst_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="product",
            name="gst_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
